/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configmodels

type DeviceGroups struct {

	Imsis []string `json:"imsis,omitempty"`

	SiteInfo string `json:"site-info,omitempty"`

	IpDomainName string `json:"ip-domain-name,omitempty"`

	IpDomainExpanded DeviceGroupsIpDomainExpanded `json:"ip-domain-expanded,omitempty"`
}
