// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configmodels

// DeviceGroupsIpDomainExpandedUeDnnQos struct for DeviceGroupsIpDomainExpandedUeDnnQos
type DeviceGroupsIpDomainExpandedUeDnnQos struct {
	// uplink data rate
	DnnMbrUplink int64 `json:"dnn-mbr-uplink,omitempty"`
	// downlink data rate
	DnnMbrDownlink int64 `json:"dnn-mbr-downlink,omitempty"`
	// data rate unit for uplink and downlink
	BitrateUnit string `json:"bitrate-unit,omitempty"`
	// QCI/QFI for the traffic
	TrafficClass *TrafficClassInfo `json:"traffic-class,omitempty"`
}
