// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configmodels

type Slice struct {
	SliceName string `json:slice-name,omitempty"`

	SliceId SliceSliceId `json:"slice-id,omitempty"`

	SiteDeviceGroup []string `json:"site-device-group"`

	SiteInfo SliceSiteInfo `json:"site-info,omitempty"`

	ApplicationFilteringRules []SliceApplicationFilteringRules `json:"application-filtering-rules,omitempty"`
}
