// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configmodels

type SliceApplicationsInformation struct {
	// Single App or group of application identification
	AppName string `json:"app-name,omitempty"`

	// Single IP or network
	Endpoint string `json:"endpoint,omitempty"`

	// port range start
	StartPort int32 `json:"start-port,omitempty"`

	// port range end
	EndPort int32 `json:"end-port,omitempty"`

	Protocol int32 `json:"protocol,omitempty"`
}
