// SPDX-FileCopyrightText: 2021 Open Networking Foundation <info@opennetworking.org>
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configmodels

type ApnAmbrQosInfo struct {
	Uplink       int32  `json:"uplink-mbr,omitempty"`
	Downlink     int32  `json:"downlink-mbr,omitempty"`
	BitRateUnit  string `json:"bitrate-unit,omitempty"`
	TrafficClass string `json:"traffic-class,omitempty"`
}
