package ssmsync

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// This function is not autogenerated
func AddSyncSSMService(engine *gin.Engine, middlewares ...gin.HandlerFunc) *gin.RouterGroup {
	group := engine.Group("/sync-ssm")
	if len(middlewares) > 0 {
		group.Use(middlewares...)
	}
	addRoutes(group, routes)
	return group
}

func addRoutes(group *gin.RouterGroup, routes Routes) {
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			group.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			group.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			group.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			group.DELETE(route.Pattern, route.HandlerFunc)
		}
	}
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Sync k4 keys and user with the SSM",
		http.MethodGet,
		"/sync-key",
		handleSyncKey,
	},
	{
		"Health check to k4 keys life",
		http.MethodGet,
		"/check-k4-life",
		handleCheckK4Life,
	},
	{
		"Init the rotation for k4 manually",
		http.MethodGet,
		"/k4-rotation",
		handleRotationKey,
	},
}
