/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configapi

// SliceSiteInfoPlmn - Fixed supported plmn at the site.
type SliceSiteInfoPlmn struct {

	Mcc string `json:"mcc,omitempty"`

	Mnc string `json:"mnc,omitempty"`
}
