/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configapi

type SliceSliceId struct {

	// Slice Service Type
	Sst int32 `json:"sst,omitempty"`

	// Slice differntiator.
	Sd int32 `json:"sd,omitempty"`
}
