/*
 * Connectivity Service Configuration
 *
 * APIs to configure connectivity service in Aether Network
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package configapi

type Slice struct {

	SliceId SliceSliceId `json:"slice-id,omitempty"`

	Qos SliceQos `json:"qos,omitempty"`

	SiteDeviceGroup []string `json:"site-device-group,omitempty"`

	SiteInfo SliceSiteInfo `json:"site-info,omitempty"`

	DenyApplications []string `json:"deny-applications,omitempty"`

	PermitApplications []string `json:"permit-applications,omitempty"`

	ApplicationsInformation []SliceApplicationsInformation `json:"applications-information,omitempty"`
}
